/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomButton`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ChatScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/config`; params?: Router.UnknownInputParams; } | { pathname: `/screens/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/GetStarted`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Logout`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SettingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TermsandCondition`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Welcomepage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CustomButton`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ChatScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/config`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/GetStarted`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Logout`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SettingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/TermsandCondition`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Welcomepage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/CustomButton${`?${string}` | `#${string}` | ''}` | `/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/screens/ChatScreen${`?${string}` | `#${string}` | ''}` | `/screens/config${`?${string}` | `#${string}` | ''}` | `/screens/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/screens/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/screens/GetStarted${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/Logout${`?${string}` | `#${string}` | ''}` | `/screens/SettingScreen${`?${string}` | `#${string}` | ''}` | `/screens/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/screens/SplashScreen${`?${string}` | `#${string}` | ''}` | `/screens/TermsandCondition${`?${string}` | `#${string}` | ''}` | `/screens/Welcomepage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomButton`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ChatScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/config`; params?: Router.UnknownInputParams; } | { pathname: `/screens/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/GetStarted`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Logout`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SettingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TermsandCondition`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Welcomepage`; params?: Router.UnknownInputParams; };
    }
  }
}
